# Generated by Django 2.0.7 on 2018-08-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True)),
                ('modified', models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('motto', models.TextField(blank=True, verbose_name='company motto')),
                ('short_description', models.TextField(verbose_name='short company description')),
                ('business_description', models.TextField()),
                ('about_description', models.TextField(verbose_name='about us')),
                ('service_description', models.TextField(verbose_name='short service description')),
                ('product_description', models.TextField(verbose_name='short product description')),
                ('contact_description', models.TextField(verbose_name='short contact description')),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=30, verbose_name='phone line 1')),
                ('phone2', models.CharField(blank=True, max_length=30, verbose_name='phone line 2')),
                ('email', models.CharField(max_length=50)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('fevicon', models.ImageField(null=True, upload_to='fevicon/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True)),
                ('modified', models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='', verbose_name='products/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True)),
                ('modified', models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product Catagory',
                'verbose_name_plural': 'Product Catagories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True)),
                ('modified', models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catagories', to='website.ProductCatagory'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='catagory',
        ),
    ]
