# Generated by Django 2.0.7 on 2018-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True)),
                ('modified', models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True)),
                ('modified', models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
