# Generated by Django 2.0.7 on 2018-08-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='FAX'),
        ),
        migrations.AddField(
            model_name='company',
            name='pobox',
            field=models.CharField(blank=True, max_length=10, verbose_name='P.O.Box'),
        ),
    ]
