# Generated by Django 2.0.7 on 2018-08-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180816_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fevicon',
            field=models.ImageField(blank=True, null=True, upload_to='fevicon/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
