# Generated by Django 2.0.7 on 2018-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180816_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='productcatagory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='productcatagory',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Record first created date and time.', null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Record last modified date and time.', null=True, verbose_name='last modified'),
        ),
    ]
