# Generated by Django 2.0.7 on 2018-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180817_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='wallpaper/'),
        ),
    ]
