# Generated by Django 2.0.7 on 2018-08-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_company_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended size is 220x220 pixels', null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wallpaper',
            field=models.ImageField(blank=True, help_text='Recommended size is 1080x960 pixels', null=True, upload_to='wallpaper/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended size is 1080x720 pixels', null=True, upload_to='products/'),
        ),
    ]
